'use client';
import './auth.css';
import Link from 'next/link';
import { FormEvent, useEffect, useState } from 'react';
import { ArrowRight, LoaderCircle } from 'lucide-react';
import { getSupabase, isSupabaseConfigured } from '../../lib/supabase-browser';

export default function AuthPage(){
 const [signup,setSignup]=useState(false),[name,setName]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[message,setMessage]=useState(''),[loading,setLoading]=useState(false);
 async function routeUser(userId:string){const {data}=await getSupabase().from('profiles').select('role').eq('id',userId).single();if(data?.role==='admin'){location.assign('/admin/dashboard');return}if(data?.role==='organizer'||data?.role==='organizer_pending'){location.assign('/organizer');return}const next=new URLSearchParams(location.search).get('next');location.assign(next?.startsWith('/')?next:'/')}
 useEffect(()=>{getSupabase().auth.getUser().then(({data})=>{if(data.user)routeUser(data.user.id)})},[]);
 async function submit(e:FormEvent){e.preventDefault();setLoading(true);setMessage('');try{const supabase=getSupabase();const result=signup?await supabase.auth.signUp({email,password,options:{data:{full_name:name,account_type:'user'},emailRedirectTo:`${location.origin}/auth`}}):await supabase.auth.signInWithPassword({email,password});if(result.error)throw result.error;if(signup)setMessage('Vérifiez votre e-mail : le lien de confirmation vient d’être envoyé.');else if(result.data.user)await routeUser(result.data.user.id)}catch(error){setMessage(error instanceof Error?error.message:'Une erreur est survenue.')}finally{setLoading(false)}}
 async function oauth(provider:'google'|'apple'){try{const {error}=await getSupabase().auth.signInWithOAuth({provider,options:{redirectTo:`${location.origin}/auth`,queryParams:{account_type:'user'}}});if(error)throw error}catch(error){setMessage(error instanceof Error?error.message:'Une erreur est survenue.')}}
 return <main className="auth-page"><Link className="brand auth-brand" href="/">NOCTURNE<span>°</span></Link><section className="auth-card"><p className="eyebrow">VOTRE ESPACE NOCTURNE</p><h1>{signup?'Créer un compte':'Bienvenue.'}</h1><p className="auth-intro">{signup?'Suivez vos artistes et gardez vos billets au même endroit.':'Connectez-vous pour retrouver votre univers.'}</p>{!isSupabaseConfigured&&<p className="auth-message">Configuration Supabase requise dans <code>.env.local</code>.</p>}<div className="oauth"><button onClick={()=>oauth('google')}>Google</button><button onClick={()=>oauth('apple')}>Apple</button></div><div className="or"><span/>ou avec votre e-mail<span/></div><form onSubmit={submit}>{signup&&<label>Prénom ou pseudo<input required value={name} onChange={e=>setName(e.target.value)} autoComplete="name"/></label>}<label>Adresse e-mail<input required type="email" value={email} onChange={e=>setEmail(e.target.value)} autoComplete="email"/></label><label>Mot de passe<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)} autoComplete={signup?'new-password':'current-password'}/></label><button className="auth-submit" disabled={loading}>{loading?<LoaderCircle className="spin" size={18}/>:<ArrowRight size={18}/>}{signup?'Créer mon compte':'Se connecter'}</button></form>{message&&<p className="auth-message">{message}</p>}<p className="switch">{signup?'Déjà inscrit ?':'Nouveau sur Nocturne ?'} <button onClick={()=>{setSignup(!signup);setMessage('')}}>{signup?'Se connecter':'Créer un compte'}</button></p></section></main>
}

