import { router, useLocalSearchParams } from 'expo-router';
import { useEffect, useState } from 'react';
import { ActivityIndicator, Image, Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { supabase } from '../lib/supabase';

type EventDetails={id:string;slug:string;title:string;description:string|null;city:string;address:string|null;starts_at:string;cover_path:string|null;ticket_types:{id:string;name:string;price_cents:number;quantity:number;sold_quantity:number}[]};

function coverUrl(path:string|null){if(!path)return null;if(path.startsWith('http'))return path;return supabase.storage.from('event-media').getPublicUrl(path).data.publicUrl}

export default function EventPage(){
  const {id}=useLocalSearchParams<{id:string}>();
  const [event,setEvent]=useState<EventDetails|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState('');
  useEffect(()=>{if(!id)return;let mounted=true;void (async()=>{const {data,error:loadError}=await supabase.from('events').select('id,slug,title,description,city,address,starts_at,cover_path,ticket_types(id,name,price_cents,quantity,sold_quantity)').eq('id',id).single();if(!mounted)return;if(loadError)setError('Cette soirée est indisponible.');else setEvent(data as EventDetails);setLoading(false)})();return()=>{mounted=false}},[id]);
  async function openTicketing(){if(!event)return;const base=(process.env.EXPO_PUBLIC_WEB_URL??'http://localhost:3000').replace(/\/$/,'');await Linking.openURL(`${base}/events/${event.slug}`)}
  if(loading)return <View style={s.center}><ActivityIndicator color="#53F6D4"/></View>;
  if(!event)return <View style={s.center}><Text style={s.error}>{error}</Text><Pressable onPress={()=>router.back()}><Text style={s.back}>← Retour</Text></Pressable></View>;
  const cover=coverUrl(event.cover_path);
  return <ScrollView style={s.page} contentContainerStyle={s.content}>{cover?<Image source={{uri:cover}} style={s.cover}/>:<View style={s.coverFallback}/>}<Pressable style={s.backButton} onPress={()=>router.back()}><Text style={s.backText}>‹</Text></Pressable><View style={s.body}><Text style={s.date}>{new Date(event.starts_at).toLocaleDateString('fr-FR',{weekday:'long',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'})}</Text><Text style={s.title}>{event.title}</Text><Text style={s.place}>{event.address?`${event.address}, `:''}{event.city}</Text>{event.description?<Text style={s.description}>{event.description}</Text>:null}<Text style={s.heading}>Billets</Text>{event.ticket_types.map(ticket=><View key={ticket.id} style={s.ticket}><View><Text style={s.ticketName}>{ticket.name}</Text><Text style={s.remaining}>{Math.max(0,ticket.quantity-ticket.sold_quantity)} disponible{ticket.quantity-ticket.sold_quantity>1?'s':''}</Text></View><Text style={s.price}>{(ticket.price_cents/100).toLocaleString('fr-FR',{style:'currency',currency:'EUR'})}</Text></View>)}<Pressable style={s.buy} onPress={()=>void openTicketing()}><Text style={s.buyText}>Accéder à la billetterie</Text></Pressable></View></ScrollView>
}

const s=StyleSheet.create({page:{flex:1,backgroundColor:'#080A14'},content:{paddingBottom:50},center:{flex:1,alignItems:'center',justifyContent:'center',gap:20,backgroundColor:'#080A14',padding:30},error:{color:'#F8F7FF',fontSize:18,textAlign:'center'},back:{color:'#53F6D4'},cover:{width:'100%',height:330},coverFallback:{height:250,backgroundColor:'#20243A'},backButton:{position:'absolute',top:55,left:20,width:42,height:42,borderRadius:21,backgroundColor:'rgba(8,10,20,.75)',alignItems:'center',justifyContent:'center'},backText:{color:'#F8F7FF',fontSize:34,lineHeight:36},body:{padding:22},date:{color:'#53F6D4',fontWeight:'800',fontSize:12,textTransform:'capitalize'},title:{color:'#F8F7FF',fontSize:36,fontWeight:'900',letterSpacing:-1.5,marginTop:10},place:{color:'#A888FF',fontWeight:'700',marginTop:10},description:{color:'#C6C8D4',lineHeight:22,marginTop:24},heading:{color:'#F8F7FF',fontSize:21,fontWeight:'900',marginTop:30,marginBottom:12},ticket:{flexDirection:'row',alignItems:'center',justifyContent:'space-between',padding:16,borderWidth:1,borderColor:'#292D42',borderRadius:14,marginBottom:10,backgroundColor:'#101321'},ticketName:{color:'#F8F7FF',fontWeight:'800'},remaining:{color:'#9FA3B8',fontSize:11,marginTop:4},price:{color:'#53F6D4',fontWeight:'900',fontSize:17},buy:{marginTop:16,padding:17,borderRadius:14,backgroundColor:'#53F6D4',alignItems:'center'},buyText:{color:'#080A14',fontWeight:'900'}});
