'use client';
import { useEffect, useMemo, useState } from 'react';
import Link from 'next/link';
import { ArrowUpRight, CalendarDays, MapPin, Search, Sparkles } from 'lucide-react';
import { eur } from '@nocturne/types';
import { events as demoEvents, posts } from '../lib/demo';
import { findFrenchCity, FRENCH_CITIES } from '../lib/french-cities';
import { getSupabase, isSupabaseConfigured } from '../lib/supabase-browser';
import AccountLink from './components/AccountLink';

type HomeEvent={id:string;slug:string;title:string;startsAt:string;city:string;genre:string|null;coverUrl:string|null;minPriceCents:number|null};
const shortDate=(iso:string)=>new Intl.DateTimeFormat('fr-FR',{weekday:'short',day:'numeric',month:'short'}).format(new Date(iso));
const comparable=(value:string)=>value.normalize('NFD').replace(/\p{Diacritic}/gu,'').trim().toLocaleLowerCase('fr-FR');
const dayKey=(iso:string)=>{const d=new Date(iso);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const fullDay=(key:string)=>new Intl.DateTimeFormat('fr-FR',{weekday:'long',day:'numeric',month:'long'}).format(new Date(`${key}T12:00:00`));

export default function Home(){
 const [events,setEvents]=useState<HomeEvent[]>([]),[loading,setLoading]=useState(true);
 const [selectedCity,setSelectedCity]=useState(''),[cityDraft,setCityDraft]=useState(''),[search,setSearch]=useState(''),[preferences,setPreferences]=useState<string[]>([]),[cityMessage,setCityMessage]=useState('');
 useEffect(()=>{async function load(){
  if(!isSupabaseConfigured){const localCity=localStorage.getItem('nocturne-city:guest')??'';setSelectedCity(localCity);setCityDraft(localCity);setEvents(demoEvents.map(e=>({id:e.id,slug:e.slug,title:e.title,startsAt:e.startsAt,city:e.city,genre:e.genre,coverUrl:e.coverUrl,minPriceCents:e.minPriceCents})));setLoading(false);return}
  try{const supabase=getSupabase();const {data:auth}=await supabase.auth.getUser();if(auth.user){const {data:profile}=await supabase.from('profiles').select('city,preferred_genres').eq('id',auth.user.id).single();const accountCity=profile?.city??localStorage.getItem(`nocturne-city:${auth.user.id}`)??'';setSelectedCity(accountCity);setCityDraft(accountCity);if(accountCity)localStorage.setItem(`nocturne-city:${auth.user.id}`,accountCity);setPreferences(profile?.preferred_genres??[])}else{const guestCity=localStorage.getItem('nocturne-city:guest')??'';setSelectedCity(guestCity);setCityDraft(guestCity)}
   const {data:eventRows,error}=await supabase.from('events').select('id,slug,title,starts_at,city,genre,cover_path,status,publish_at').neq('status','cancelled').order('starts_at');if(error)throw error;const now=new Date();const publicRows=(eventRows??[]).filter(e=>(e.status==='published'||(e.publish_at&&new Date(e.publish_at)<=now))&&new Date(e.starts_at)>=now);const ids=publicRows.map(e=>e.id);const {data:tickets}=ids.length?await supabase.from('ticket_types').select('event_id,price_cents').in('event_id',ids):{data:[]};setEvents(publicRows.map(e=>{const prices=(tickets??[]).filter(t=>t.event_id===e.id).map(t=>t.price_cents);return{id:e.id,slug:e.slug,title:e.title,startsAt:e.starts_at,city:e.city,genre:e.genre,coverUrl:e.cover_path?supabase.storage.from('event-media').getPublicUrl(e.cover_path).data.publicUrl:null,minPriceCents:prices.length?Math.min(...prices):null}}));
  }catch(error){console.error('Impossible de charger les soirées :',error);setEvents([])}finally{setLoading(false)}}load()},[]);
 async function chooseCity(){const city=findFrenchCity(cityDraft);setCityMessage('');if(!city){setCityMessage('Choisissez une ville proposée dans la liste.');return}if(isSupabaseConfigured){const supabase=getSupabase();const {data:auth}=await supabase.auth.getUser();if(auth.user){const {error}=await supabase.from('profiles').update({city:city.name,latitude:city.latitude,longitude:city.longitude}).eq('id',auth.user.id);if(error){setCityMessage('La ville n’a pas pu être enregistrée.');return}localStorage.setItem(`nocturne-city:${auth.user.id}`,city.name)}else localStorage.setItem('nocturne-city:guest',city.name)}else localStorage.setItem('nocturne-city:guest',city.name);setSelectedCity(city.name);setCityDraft(city.name)}
 const cityEvents=useMemo(()=>events.filter(event=>!selectedCity||comparable(event.city)===comparable(selectedCity)),[events,selectedCity]);
 const searched=useMemo(()=>{const query=comparable(search);const source=query?events:cityEvents;return source.filter(event=>!query||comparable(`${event.title} ${event.genre??''} ${event.city}`).includes(query))},[events,cityEvents,search]);
 const groups=useMemo(()=>{const preferred=new Set(preferences.map(comparable)),map=new Map<string,HomeEvent[]>();for(const event of searched){const key=dayKey(event.startsAt);map.set(key,[...(map.get(key)??[]),event])}return [...map.entries()].sort(([a],[b])=>a.localeCompare(b)).map(([key,items])=>[key,items.sort((a,b)=>{const scoreA=a.genre?Number(preferred.has(comparable(a.genre))):0,scoreB=b.genre?Number(preferred.has(comparable(b.genre))):0;return scoreB-scoreA||a.startsAt.localeCompare(b.startsAt)})] as const)},[searched,preferences]);
 const isPreferred=(event:HomeEvent)=>event.genre?preferences.some(pref=>comparable(pref)===comparable(event.genre as string)):false;
 return <main><nav className="home-nav"><Link className="brand" href="/">NOCTURNE<span>°</span></Link><div className="nav-discovery"><div className="global-city"><MapPin size={17}/><div><label htmlFor="global-city">Ville du fil</label><input id="global-city" list="global-cities" value={cityDraft} onChange={e=>setCityDraft(e.target.value)} onBlur={chooseCity} onKeyDown={e=>{if(e.key==='Enter')chooseCity()}} placeholder="Ville"/><datalist id="global-cities">{FRENCH_CITIES.map(city=><option key={city.name} value={city.name}/>)}</datalist></div></div><label className="global-search"><Search size={17}/><div><span>Recherche globale</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Soirée, festival ou style"/></div></label></div><div className="navlinks"><a href="#events">Soirées</a><a href="#feed">Fil artiste</a></div><Link className="pro-entry" href="/organizer/auth">Je suis une organisation <ArrowUpRight size={14}/></Link><AccountLink/></nav>{cityMessage&&<p className="global-city-error nav-city-error">{cityMessage}</p>}
 <section className="hero"><p className="eyebrow"><Sparkles size={14}/> LA NUIT VOUS APPARTIENT</p><h1>Trouvez les nuits<br/><i>qui vous trouvent.</i></h1><p className="lede">Suivez les artistes que vous aimez. Découvrez leurs soirées, leurs nouveaux sons et vivez-les au premier rang.</p><a className="cta" href="#events">Explorer les soirées <ArrowUpRight size={18}/></a><div className="orb one"/><div className="orb two"/></section>
 <section id="events" className="content upcoming-feed"><div className="section-head"><div><p className="eyebrow">{search?'RECHERCHE GLOBALE':<>AGENDA {selectedCity&&`· ${selectedCity.toLocaleUpperCase('fr')}`}</>}</p><h2>{search?'Résultats de recherche':'Les prochaines soirées'}</h2></div><span className="event-count">{searched.length} soirée{searched.length>1?'s':''}</span></div>{loading?<div className="events-empty">Chargement des soirées...</div>:!selectedCity&&!search?<div className="events-empty">Choisissez votre ville en haut de la page pour afficher les prochaines soirées.</div>:groups.length?groups.map(([key,items])=><section className="event-day" key={key}><header><span>{fullDay(key)}</span><i/></header><div className="event-day-list">{items.map((event,index)=><Link href={`/events/${event.slug}`} className="event-feed-row" key={event.id}>{event.coverUrl?<img src={event.coverUrl} alt=""/>:<div className="event-feed-cover">NOCTURNE°</div>}<div className="event-feed-info"><span>{new Date(event.startsAt).toLocaleTimeString('fr-FR',{hour:'2-digit',minute:'2-digit'})} · {event.genre??'Soirée'}</span><h3>{event.title}</h3><p>{event.city}{event.minPriceCents!==null?` · Dès ${eur(event.minPriceCents)}`:''}</p></div>{index===0&&isPreferred(event)&&<em>Pour vous</em>}<ArrowUpRight size={19}/></Link>)}</div></section>):<div className="events-empty">{search?'Aucune soirée ou aucun festival ne correspond à cette recherche.':'Aucune soirée à venir trouvée dans cette ville.'}</div>}</section>
 <section id="feed" className="feed-section"><div className="section-head"><div><p className="eyebrow">DE VOS ARTISTES</p><h2>Dans votre fil</h2></div><button className="ghost">Gérer mes suivis</button></div><div className="feed-grid">{posts.map(post=><article className="post" key={post.id}>{post.mediaUrl&&<img src={post.mediaUrl} alt=""/>}<div className="post-body"><div className="artist"><img src={post.artist.avatarUrl} alt=""/><span><b>{post.artist.displayName} <em>✓</em></b><small>{post.createdAt}</small></span><button>Suivre</button></div><p>{post.body}</p>{post.event&&<Link href={`/events/${post.event.slug}`} className="post-event"><CalendarDays size={17}/><span><b>{post.event.title}</b><small>{shortDate(post.event.startsAt)} · {post.event.city}</small></span><ArrowUpRight size={17}/></Link>}</div></article>)}</div></section><footer><span>© 2026 NOCTURNE</span><span>La culture live, autrement.</span></footer></main>
}

