import Link from 'next/link';
import { ArrowUpRight, CalendarDays, MapPin, Sparkles } from 'lucide-react';
import { eur } from '@nocturne/types';
import { events, posts } from '../lib/demo';

const date = (iso: string) => new Intl.DateTimeFormat('fr-FR', { weekday: 'short', day: 'numeric', month: 'short' }).format(new Date(iso));
export default function Home() { return <main><nav><Link className="brand" href="/">NOCTURNE<span>°</span></Link><div className="navlinks"><a href="#events">Soirées</a><a href="#feed">Fil artiste</a><Link href="/organizer">Organisateurs</Link></div><Link className="account" href="/auth">Se connecter</Link></nav>
  <section className="hero"><p className="eyebrow"><Sparkles size={14}/> LA NUIT VOUS APPARTIENT</p><h1>Trouvez les nuits<br/><i>qui vous trouvent.</i></h1><p className="lede">Suivez les artistes que vous aimez. Découvrez leurs soirées, leurs nouveaux sons et vivez-les au premier rang.</p><a className="cta" href="#events">Explorer les soirées <ArrowUpRight size={18}/></a><div className="orb one"/><div className="orb two"/></section>
  <section id="events" className="content"><div className="section-head"><div><p className="eyebrow">SÉLECTION</p><h2>Ce week-end</h2></div><a href="#">Voir tout <ArrowUpRight size={17}/></a></div><div className="event-grid">{events.map((event, index) => <Link href={`/events/${event.slug}`} className={`event-card c${index + 1}`} key={event.id}><img src={event.coverUrl} alt=""/><div className="shade"/><div className="event-meta"><span>{date(event.startsAt)} · {event.city}</span><h3>{event.title}</h3><p>{event.venueName} · Dès {eur(event.minPriceCents)}</p></div></Link>)}</div></section>
  <section id="feed" className="feed-section"><div className="section-head"><div><p className="eyebrow">DE VOS ARTISTES</p><h2>Dans votre fil</h2></div><button className="ghost">Gérer mes suivis</button></div><div className="feed-grid">{posts.map(post => <article className="post" key={post.id}>{post.mediaUrl && <img src={post.mediaUrl} alt=""/>}<div className="post-body"><div className="artist"><img src={post.artist.avatarUrl} alt=""/><span><b>{post.artist.displayName} <em>✓</em></b><small>{post.createdAt}</small></span><button>Suivre</button></div><p>{post.body}</p>{post.event && <Link href={`/events/${post.event.slug}`} className="post-event"><CalendarDays size={17}/><span><b>{post.event.title}</b><small>{date(post.event.startsAt)} · {post.event.city}</small></span><ArrowUpRight size={17}/></Link>}</div></article>)}</div></section>
  <footer><span>© 2026 NOCTURNE</span><span>La culture live, autrement.</span></footer></main>; }
