'use client';

import { useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, LoaderCircle, Save } from 'lucide-react';
import { getSupabase } from '../../../lib/supabase-browser';

type Organization={profile_id:string;name:string;primary_fee_bps:number;primary_fee_min_cents:number;resale_fee_bps:number;resale_fee_cap_cents:number;onboarding_complete:boolean;role:'organizer'|'organizer_pending'};

export default function OrganizationsAdminPage(){
 const [state,setState]=useState<'loading'|'forbidden'|'ready'>('loading'),[organizations,setOrganizations]=useState<Organization[]>([]),[saving,setSaving]=useState<string|null>(null),[error,setError]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{void (async()=>{const supabase=getSupabase(),{data:auth}=await supabase.auth.getUser();if(!auth.user){setState('forbidden');return}const {data:profile}=await supabase.from('profiles').select('role').eq('id',auth.user.id).single();if(profile?.role!=='admin'){setState('forbidden');return}const {data,error}=await supabase.from('organizer_profiles').select('profile_id,name,primary_fee_bps,primary_fee_min_cents,resale_fee_bps,resale_fee_cap_cents,onboarding_complete').order('name');if(error){setError(error.message);setState('ready');return}const ids=(data??[]).map(item=>item.profile_id),{data:roles}=ids.length?await supabase.from('profiles').select('id,role').in('id',ids):{data:[]};const roleMap=new Map((roles??[]).map(item=>[item.id,item.role]));setOrganizations((data??[]).filter(item=>['organizer','organizer_pending'].includes(roleMap.get(item.profile_id)??'')).map(item=>({...item,role:roleMap.get(item.profile_id)==='organizer'?'organizer':'organizer_pending'})));setState('ready')})()},[]);
 function change(id:string,key:'primary_fee_bps'|'primary_fee_min_cents'|'resale_fee_bps'|'resale_fee_cap_cents',value:number){setOrganizations(current=>current.map(item=>item.profile_id===id?{...item,[key]:key.endsWith('_bps')?Math.round(value*100):Math.round(value*100)}:item))}
 async function save(organization:Organization){setSaving(organization.profile_id);setError('');setMessage('');const {error}=await getSupabase().rpc('set_organizer_fee_rates',{p_organizer:organization.profile_id,p_primary_bps:organization.primary_fee_bps,p_primary_min_cents:organization.primary_fee_min_cents,p_resale_bps:organization.resale_fee_bps,p_resale_cap_cents:organization.resale_fee_cap_cents});if(error)setError(error.message);else setMessage(`Commissions de ${organization.name} enregistrées.`);setSaving(null)}
 async function setApproval(organization:Organization,approved:boolean){setSaving(organization.profile_id);setError('');const {error}=await getSupabase().rpc('set_organizer_account_approval',{p_organizer:organization.profile_id,p_approved:approved});if(error)setError(error.message);else{setOrganizations(current=>current.map(item=>item.profile_id===organization.profile_id?{...item,role:approved?'organizer':'organizer_pending'}:item));setMessage(approved?`${organization.name} peut désormais publier.`:`${organization.name} a été remis en attente.`)}setSaving(null)}
 if(state==='loading')return <main className="dashboard"><LoaderCircle className="spin"/></main>;
 if(state==='forbidden')return <main className="dashboard organizer-access"><h1>Administration uniquement.</h1><Link href="/"><ArrowLeft/>Retour</Link></main>;
 return <main className="dashboard fee-admin"><nav><Link className="brand" href="/">NOCTURNE<span>°</span></Link><Link className="profile-back" href="/organizer/dashboard"><ArrowLeft size={16}/>Retour</Link></nav><header className="dash-head"><div><p className="eyebrow">ADMINISTRATION</p><h1>Commissions organisations.</h1><p>Par défaut : 3,5 % avec un minimum de 0,49 € sur les ventes, puis 10 % plafonnés à 15 € sur les reventes.</p></div></header>{error&&<p className="profile-error">{error}</p>}{message&&<p className="profile-success">{message}</p>}<section className="fee-organization-list">{organizations.map(organization=><article className="fee-organization-card" key={organization.profile_id}><div><h2>{organization.name}</h2><small>{organization.onboarding_complete?'Stripe opérationnel':'Stripe à configurer'}</small></div><label>Vente initiale <span><input type="number" min="0" max="50" step="0.1" value={organization.primary_fee_bps/100} onChange={event=>change(organization.profile_id,'primary_fee_bps',Number(event.target.value))}/>%</span></label><label>Minimum / billet <span><input type="number" min="0" max="100" step="0.01" value={organization.primary_fee_min_cents/100} onChange={event=>change(organization.profile_id,'primary_fee_min_cents',Number(event.target.value))}/>€</span></label><label>Revente <span><input type="number" min="0" max="50" step="0.1" value={organization.resale_fee_bps/100} onChange={event=>change(organization.profile_id,'resale_fee_bps',Number(event.target.value))}/>%</span></label><label>Plafond / billet <span><input type="number" min="0" max="1000" step="0.01" value={organization.resale_fee_cap_cents/100} onChange={event=>change(organization.profile_id,'resale_fee_cap_cents',Number(event.target.value))}/>€</span></label><div className="fee-account-status"><b>{organization.role==='organizer'?'Validée':'En attente'}</b><button type="button" disabled={saving===organization.profile_id} onClick={()=>void setApproval(organization,organization.role!=='organizer')}>{organization.role==='organizer'?'Suspendre':'Valider le compte'}</button></div><button className="cta" disabled={saving===organization.profile_id} onClick={()=>void save(organization)}>{saving===organization.profile_id?<LoaderCircle className="spin" size={16}/>:<Save size={16}/>}Enregistrer</button></article>)}</section></main>;
}
