export const MUSIC_GENRES = [
  'Acid House', 'Acid Techno', 'Afro House', 'Afrobeat', 'Afrobeats', 'Amapiano',
  'Ambient', 'Bass House', 'Bass Music', 'Bebop', 'Black Metal', 'Blues', 'Breakbeat',
  'Breakcore', 'Chicago House', 'Chillout', 'Cloud Rap', 'Cold Wave', 'Country',
  'Dancehall', 'Dark Disco', 'Dark Techno', 'Death Metal', 'Deep House', 'Disco',
  'Doom Metal', 'Dream Pop', 'Drill', 'Drum & Bass', 'Dub', 'Dub Techno', 'Dubstep',
  'EBM', 'Electro', 'Electro Swing', 'Electronica', 'Emo', 'Eurodance',
  'Experimental', 'French Touch', 'Frenchcore', 'Funk', 'Gabber', 'Garage',
  'Ghetto House', 'Glam Rock', 'Goa Trance', 'Gospel', 'Grime', 'Grindcore',
  'Groove Metal', 'Grunge', 'Happy Hardcore', 'Hard House', 'Hard Techno',
  'Hard Trance', 'Hardcore', 'Hardstyle', 'Hi-NRG', 'Hip-Hop', 'House',
  'Hyperpop', 'Indie Dance', 'Indie Pop', 'Indie Rock', 'Industrial',
  'Industrial Techno', 'Italo Disco', 'Jazz', 'Jungle', 'Latin', 'Lo-fi',
  'Melodic House', 'Melodic Techno', 'Metal', 'Metalcore', 'Minimal',
  'Minimal Techno', 'Neo Soul', 'New Wave', 'Noise', 'Nu Disco', 'Nu Metal',
  'Organic House', 'Pop', 'Post-Punk', 'Post-Rock', 'Power Metal',
  'Progressive House', 'Progressive Metal', 'Progressive Trance', 'Psytrance',
  'Punk', 'R&B', 'Rap', 'Reggae', 'Reggaeton', 'Rock', 'Rock alternatif',
  'Schranz', 'Shoegaze', 'Soul', 'Speedcore', 'Stoner Rock', 'Synthpop',
  'Synthwave', 'Tech House', 'Techno', 'Trance', 'Trap', 'Tribe', 'Trip-Hop',
  'UK Garage', 'Uptempo', 'Vaporwave', 'World Music',
] as const;
