'use client';
import { useEffect, useState } from 'react';
import Link from 'next/link';
import { useParams, useSearchParams } from 'next/navigation';
import { ArrowLeft, Building2, CalendarDays, Heart, LoaderCircle, MapPin, Minus, Music2, Plus, Star, Ticket, X } from 'lucide-react';
import { eur } from '@nocturne/types';
import { events as demoEvents, ticketTypes as demoTicketTypes } from '../../../lib/demo';
import { getSupabase, isSupabaseConfigured } from '../../../lib/supabase-browser';
import EmbeddedCheckout from '../../components/EmbeddedCheckout';

type EventView={id:string;slug:string;title:string;description:string|null;starts_at:string;ends_at:string|null;city:string;address:string|null;genre:string|null;cover_path:string|null;organizer_id:string};
type TicketView={id:string;name:string;price_cents:number;quantity?:number;sold_quantity?:number};

export default function EventPage(){
 const {slug}=useParams<{slug:string}>();
 const organizerPreview=useSearchParams().get('preview')==='organizer';
 const [event,setEvent]=useState<EventView|null>(null),[tickets,setTickets]=useState<TicketView[]>([]),[loading,setLoading]=useState(true),[userId,setUserId]=useState<string|null>(null);
 const [quantities,setQuantities]=useState<Record<string,number>>({}),[checkoutLoading,setCheckoutLoading]=useState(false),[checkoutError,setCheckoutError]=useState(''),[checkoutSession,setCheckoutSession]=useState<{clientSecret:string;publishableKey:string}|null>(null);
 const [rating,setRating]=useState(0),[feedback,setFeedback]=useState(''),[reviewSaving,setReviewSaving]=useState(false),[reviewMessage,setReviewMessage]=useState(''),[reviewError,setReviewError]=useState('');
 const [organizerName,setOrganizerName]=useState('Organisation Nocturne'),[interestCount,setInterestCount]=useState(0),[interested,setInterested]=useState(false);
 const [ticketPanelOpen,setTicketPanelOpen]=useState(false),[compactTicketVisible,setCompactTicketVisible]=useState(false);
 useEffect(()=>{async function load(){if(isSupabaseConfigured){const supabase=getSupabase();const {data}=await supabase.from('events').select('id,slug,title,description,starts_at,ends_at,city,address,genre,cover_path,organizer_id').eq('slug',slug).maybeSingle();if(data){setEvent(data);const [{data:ticketData},{data:auth},{data:organization},{count}]=await Promise.all([supabase.from('ticket_types').select('id,name,price_cents').eq('event_id',data.id).order('position'),supabase.auth.getUser(),supabase.from('organizer_profiles').select('name').eq('profile_id',data.organizer_id).maybeSingle(),supabase.from('event_interests').select('*',{count:'exact',head:true}).eq('event_id',data.id)]);setTickets(ticketData??[]);setOrganizerName(organization?.name??'Organisation Nocturne');setInterestCount(count??0);if(auth.user){setUserId(auth.user.id);const [{data:review},{data:interest}]=await Promise.all([supabase.from('event_reviews').select('rating,feedback').eq('event_id',data.id).eq('reviewer_id',auth.user.id).maybeSingle(),supabase.from('event_interests').select('event_id').eq('event_id',data.id).eq('user_id',auth.user.id).maybeSingle()]);setInterested(Boolean(interest));if(review){setRating(review.rating);setFeedback(review.feedback??'')}}setLoading(false);return}}const demo=demoEvents.find(item=>item.slug===slug);if(demo){setEvent({id:demo.id,slug:demo.slug,title:demo.title,description:null,starts_at:demo.startsAt,ends_at:null,city:demo.city,address:null,genre:demo.genre,cover_path:demo.coverUrl,organizer_id:''});setTickets(demoTicketTypes.filter(item=>item.eventId===demo.id).map(item=>({id:item.id,name:item.name,price_cents:item.priceCents})))}setLoading(false)}load()},[slug]);
 useEffect(()=>{if(!event||!isSupabaseConfigured)return;getSupabase().from('ticket_types').select('id,name,price_cents,quantity,sold_quantity').eq('event_id',event.id).order('position').then(({data})=>{if(data)setTickets(data)})},[event?.id]);
 useEffect(()=>{const onScroll=()=>{const box=document.querySelector('.buy-box');if(!box)return;setCompactTicketVisible(box.getBoundingClientRect().bottom<90)};onScroll();addEventListener('scroll',onScroll,{passive:true});return()=>removeEventListener('scroll',onScroll)},[]);
 if(loading)return <main><section className="profile-loading">Chargement...</section></main>;
 if(!event)return <main><section className="profile-error"><p className="eyebrow">SOIRÉE INTROUVABLE</p><h1>Cette soirée n’est pas disponible.</h1><Link className="cta" href="/"><ArrowLeft size={16}/>Retour</Link></section></main>;
 const eventId=event.id;
 const coverUrl=event.cover_path?.startsWith('http')?event.cover_path:event.cover_path?getSupabase().storage.from('event-media').getPublicUrl(event.cover_path).data.publicUrl:null;
 const format=(value:string)=>new Intl.DateTimeFormat('fr-FR',{dateStyle:'full',timeStyle:'short'}).format(new Date(value));
 const finished=new Date(event.ends_at||event.starts_at)<new Date(),selectedCount=Object.values(quantities).reduce((sum,value)=>sum+value,0),total=tickets.reduce((sum,ticket)=>sum+ticket.price_cents*(quantities[ticket.id]??0),0);
 const availableTickets=tickets.filter(ticket=>ticket.quantity===undefined||(ticket.sold_quantity??0)<ticket.quantity),cheapestAvailable=availableTickets.length?Math.min(...availableTickets.map(ticket=>ticket.price_cents)):null;
 function openTickets(){if(innerWidth<=800){setTicketPanelOpen(true);document.body.style.overflow='hidden'}else document.querySelector('.buy-box')?.scrollIntoView({behavior:'smooth',block:'center'})}
 function closeTickets(){setTicketPanelOpen(false);document.body.style.overflow=''}
 async function checkout(){const items=tickets.map(ticket=>({ticketTypeId:ticket.id,quantity:quantities[ticket.id]??0})).filter(item=>item.quantity>0);if(!items.length)return;if(!userId){location.assign(`/auth?next=${encodeURIComponent(`/events/${slug}`)}`);return}setCheckoutLoading(true);setCheckoutError('');try{const {data,error}=await getSupabase().functions.invoke('create-checkout-session',{body:{items}});if(error){let message=error.message;const context=(error as {context?:Response}).context;if(context){try{const body=await context.clone().json();message=body.error||message}catch{}}throw new Error(message)}if(!data?.clientSecret||!data?.publishableKey)throw new Error(data?.error||'Session de paiement indisponible');setCheckoutSession({clientSecret:data.clientSecret,publishableKey:data.publishableKey})}catch(error){setCheckoutError(error instanceof Error?error.message:'Impossible de démarrer le paiement.')}finally{setCheckoutLoading(false)}}
 async function saveReview(){if(!userId||!rating)return;setReviewSaving(true);setReviewError('');setReviewMessage('');const {error}=await getSupabase().from('event_reviews').upsert({event_id:eventId,reviewer_id:userId,rating,feedback:feedback.trim()||null,updated_at:new Date().toISOString()},{onConflict:'event_id,reviewer_id'});if(error)setReviewError('Impossible d’enregistrer votre avis.');else setReviewMessage('Merci, votre retour a été transmis à l’organisation.');setReviewSaving(false)}
 async function toggleInterest(){if(!userId){location.assign(`/auth?next=${encodeURIComponent(`/events/${slug}`)}`);return}const supabase=getSupabase();if(interested){const {error}=await supabase.from('event_interests').delete().eq('event_id',eventId).eq('user_id',userId);if(!error){setInterested(false);setInterestCount(value=>Math.max(0,value-1))}}else{const {error}=await supabase.from('event_interests').insert({event_id:eventId,user_id:userId});if(!error){setInterested(true);setInterestCount(value=>value+1)}}}
 return <main>
  <nav><Link className="brand" href={organizerPreview?"/organizer":"/"}>NOCTURNE<span>°</span></Link><Link className="back" href={organizerPreview?"/organizer":"/"}><ArrowLeft size={16}/>{organizerPreview?"Retour à l’espace organisation":"Retour"}</Link></nav>
  {!organizerPreview&&cheapestAvailable!==null&&<button className={`compact-ticket-cta ${compactTicketVisible?'visible':''}`} onClick={openTickets}><Ticket size={17}/><span>Maintenant à <strong>{eur(cheapestAvailable)}</strong></span></button>}
  <section className="detail">
   {coverUrl?<img className="detail-cover" src={coverUrl} alt=""/>:<div className="detail-cover event-cover-fallback"><span>NOCTURNE°</span></div>}
   <div className="detail-info"><p className="eyebrow">{event.genre||'SOIRÉE'}</p><h1>{event.title}</h1><div className="details"><p><CalendarDays/>{format(event.starts_at)}{event.ends_at&&<> — {format(event.ends_at)}</>}</p><p><MapPin/>{event.address||event.city}</p></div><button className={`event-interest ${interested?'active':''}`} onClick={toggleInterest}><Heart fill={interested?'currentColor':'none'}/>{interested?'Intéressé·e':'Ça m’intéresse'}<span>{interestCount}</span></button></div>
   {!organizerPreview&&<aside className={`buy-box ${checkoutSession?'checkout-active':''} ${ticketPanelOpen?'mobile-open':''}`}>
    <button className="mobile-ticket-close" onClick={closeTickets}><X/>Fermer</button>
    {checkoutSession?<EmbeddedCheckout {...checkoutSession} onClose={()=>setCheckoutSession(null)}/>:<>
     <p className="eyebrow">BILLETTERIE SÉCURISÉE</p><h2>Choisir vos billets</h2>
     {tickets.map(ticket=>{const quantity=quantities[ticket.id]??0,remaining=ticket.quantity===undefined?Infinity:Math.max(0,ticket.quantity-(ticket.sold_quantity??0)),soldOut=remaining===0;return <div className={`ticket-row ${soldOut?'sold-out':''}`} key={ticket.id}><span><b>{ticket.name}</b><small>{eur(ticket.price_cents)}</small></span>{soldOut?<span className="ticket-sold-out">Épuisé</span>:<div className="ticket-quantity"><button type="button" aria-label={`Retirer un billet ${ticket.name}`} disabled={quantity===0} onClick={()=>setQuantities(current=>({...current,[ticket.id]:Math.max(0,quantity-1)}))}><Minus size={16}/></button><b>{quantity}</b><button type="button" aria-label={`Ajouter un billet ${ticket.name}`} disabled={selectedCount>=10||quantity>=remaining} onClick={()=>setQuantities(current=>({...current,[ticket.id]:quantity+1}))}><Plus size={16}/></button></div>}</div>})}
     {tickets.length===0&&<p className="profile-empty">Billetterie bientôt disponible.</p>}
     <div className="checkout-total"><span>Total</span><strong>{eur(total)}</strong></div>{checkoutError&&<p className="profile-error">{checkoutError}</p>}
     <button className="buy" type="button" onClick={checkout} disabled={!selectedCount||checkoutLoading}>{checkoutLoading?'Préparation du paiement…':'Continuer vers le paiement'}</button>
     <small>Vos QR codes seront disponibles uniquement dans l’espace Billets de l’application.</small>
    </>}
   </aside>}
  </section>
  <section className="event-story"><article><p className="eyebrow">À PROPOS</p><h2>L’expérience.</h2><div className="event-description">{(event.description||'Une nuit pensée par la communauté Nocturne.').split('\n').map((line,index)=><p key={index}>{line}</p>)}</div></article><aside><div className="event-organizer"><Building2/><span><small>Organisé par</small><strong>{organizerName}</strong></span></div>{event.genre&&<div className="event-vibes"><Music2/><span><small>Styles choisis</small><strong>{event.genre}</strong></span></div>}<div className="event-rules"><h3>Règles du lieu</h3><p>Respectez le lieu, les équipes et les autres participant·es. Les règles détaillées sont communiquées par l’organisation.</p></div></aside></section>
  <section className="event-location"><p className="eyebrow">LOCALISATION</p><h2>{event.address||event.city}</h2><iframe title={`Carte de ${event.title}`} loading="lazy" referrerPolicy="no-referrer-when-downgrade" src={`https://www.google.com/maps?q=${encodeURIComponent(event.address||event.city)}&output=embed`}/></section>
  {finished&&<section className="event-review"><div className="event-review-card"><p className="eyebrow">VOTRE RETOUR</p><h2>Comment était cette soirée ?</h2>{userId?<><div className="event-rating-buttons">{[1,2,3,4,5].map(value=><button className={value<=rating?'active':''} type="button" aria-label={`${value} étoile${value>1?'s':''}`} onClick={()=>setRating(value)} key={value}><Star size={20} fill={value<=rating?'currentColor':'none'}/></button>)}</div><textarea maxLength={2000} value={feedback} onChange={e=>setFeedback(e.target.value)} placeholder="Un commentaire pour l’organisation (facultatif)"/><button className="cta" type="button" disabled={!rating||reviewSaving} onClick={saveReview}>{reviewSaving?<LoaderCircle className="spin" size={17}/>:<Star size={17}/>}Envoyer mon avis</button>{reviewMessage&&<span className="profile-success">{reviewMessage}</span>}{reviewError&&<span className="profile-error">{reviewError}</span>}</>:<Link className="cta" href="/auth">Se connecter pour laisser un avis</Link>}</div></section>}
 </main>
}

