'use client';
import { ChangeEvent, FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ImagePlus, LoaderCircle, Plus, Save, Trash2 } from 'lucide-react';
import { useParams } from 'next/navigation';
import { getSupabase } from '../../../../lib/supabase-browser';
import { MUSIC_GENRES } from '../../../../lib/music-genres';

type Phase={id:string;name:string;quantity:string;price:string;sold:number};
const parts=(value:string|null)=>{if(!value)return {date:'',time:''};const d=new Date(value),pad=(n:number)=>String(n).padStart(2,'0');return {date:`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`,time:`${pad(d.getHours())}:${pad(d.getMinutes())}`}};

export default function EditEventPage(){
 const {id}=useParams<{id:string}>();
 const [loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('');
 const [slug,setSlug]=useState(''),[title,setTitle]=useState(''),[city,setCity]=useState(''),[genre,setGenre]=useState(''),[description,setDescription]=useState('');
 const [startDate,setStartDate]=useState(''),[startTime,setStartTime]=useState(''),[endDate,setEndDate]=useState(''),[endTime,setEndTime]=useState(''),[capacity,setCapacity]=useState('');
 const [publication,setPublication]=useState<'draft'|'now'|'scheduled'>('draft'),[publishDate,setPublishDate]=useState(''),[publishTime,setPublishTime]=useState('');
 const [phases,setPhases]=useState<Phase[]>([]),[bannerFile,setBannerFile]=useState<File|null>(null),[bannerUrl,setBannerUrl]=useState<string|null>(null);
 useEffect(()=>{async function load(){try{const supabase=getSupabase();const [{data:event,error:eventError},{data:settings},{data:tickets}]=await Promise.all([supabase.from('events').select('*').eq('id',id).single(),supabase.from('event_private_settings').select('max_capacity').eq('event_id',id).single(),supabase.from('ticket_types').select('id,name,quantity,price_cents,sold_quantity').eq('event_id',id).order('price_cents')]);if(eventError)throw eventError;setSlug(event.slug);setTitle(event.title);setCity(event.city);setGenre(event.genre??'');setDescription(event.description??'');const start=parts(event.starts_at),end=parts(event.ends_at),publish=parts(event.publish_at);setStartDate(start.date);setStartTime(start.time);setEndDate(end.date);setEndTime(end.time);setPublishDate(publish.date);setPublishTime(publish.time);setPublication(event.status==='published'?'now':event.publish_at?'scheduled':'draft');setCapacity(String(settings?.max_capacity??''));setPhases((tickets??[]).map(ticket=>({id:ticket.id,name:ticket.name,quantity:String(ticket.quantity),price:(ticket.price_cents/100).toFixed(2),sold:ticket.sold_quantity})));if(event.cover_path)setBannerUrl(supabase.storage.from('event-media').getPublicUrl(event.cover_path).data.publicUrl)}catch(loadError){console.error(loadError);setError('Impossible de charger cette soirée.')}finally{setLoading(false)}}load()},[id]);
 function banner(event:ChangeEvent<HTMLInputElement>){const file=event.target.files?.[0];if(!file)return;if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>10*1024*1024){setError('Bannière JPG, PNG ou WebP de 10 Mo maximum.');return}if(bannerUrl?.startsWith('blob:'))URL.revokeObjectURL(bannerUrl);setBannerFile(file);setBannerUrl(URL.createObjectURL(file))}
 async function submit(event:FormEvent){event.preventDefault();setSaving(true);setError('');setMessage('');try{const total=phases.reduce((sum,p)=>sum+Number(p.quantity),0);if(total>Number(capacity))throw new Error('capacity');const start=new Date(`${startDate}T${startTime}`),end=new Date(`${endDate}T${endTime}`);const publishAt=publication==='scheduled'?new Date(`${publishDate}T${publishTime}`).toISOString():null;const supabase=getSupabase();const {error:updateError}=await supabase.rpc('update_event_with_phases',{p_event_id:id,p_title:title,p_city:city,p_starts_at:start.toISOString(),p_ends_at:end.toISOString(),p_max_capacity:Number(capacity),p_ticket_phases:phases.map(p=>({id:p.id||null,name:p.name,quantity:Number(p.quantity),price_cents:Math.round(Number(p.price)*100)})),p_description:description||null,p_genre:genre||null,p_publication:publication,p_publish_at:publishAt});if(updateError)throw updateError;if(bannerFile){const {data:auth}=await supabase.auth.getUser();if(!auth.user)throw new Error('auth');const path=`${auth.user.id}/${id}/banner`;const {error:uploadError}=await supabase.storage.from('event-media').upload(path,bannerFile,{upsert:true,contentType:bannerFile.type,cacheControl:'3600'});if(uploadError)throw uploadError;const {error:bannerError}=await supabase.rpc('set_event_banner',{p_event_id:id,p_cover_path:path});if(bannerError)throw bannerError;setBannerUrl(`${supabase.storage.from('event-media').getPublicUrl(path).data.publicUrl}?v=${Date.now()}`);setBannerFile(null)}setMessage('Soirée mise à jour.')}catch(saveError){console.error(saveError);setError(saveError instanceof Error&&saveError.message==='capacity'?'Les phases dépassent la capacité maximale.':'Impossible d’enregistrer les modifications. Une phase vendue ne peut pas être supprimée ni réduite sous ses ventes.')}finally{setSaving(false)}}
 if(loading)return <main className="dashboard"><LoaderCircle className="spin"/></main>;
 if(error&&!title)return <main className="dashboard organizer-access"><h1>{error}</h1><Link className="profile-back" href="/organizer"><ArrowLeft size={16}/>Retour</Link></main>;
 const total=phases.reduce((sum,p)=>sum+(Number(p.quantity)||0),0);
 return <main className="dashboard organizer-create"><nav><Link className="brand" href="/">NOCTURNE<span>°</span></Link><Link className="profile-back profile-nav-back" href="/organizer"><ArrowLeft size={16}/>Mes soirées</Link></nav><header className="dash-head"><div><p className="eyebrow">MODIFICATION</p><h1>{title}</h1><p>/events/{slug}</p></div><Link className="profile-edit" href={`/events/${slug}`}>Aperçu public</Link></header><form className="event-create-form" onSubmit={submit}>
 <div className="profile-field"><label>Nom de la soirée</label><input required minLength={3} value={title} onChange={e=>setTitle(e.target.value)}/></div>
 <div className="profile-field"><label>Ville</label><input required value={city} onChange={e=>setCity(e.target.value)}/></div>
 <fieldset className="event-datetime"><legend>Début et fin</legend><div className="event-form-grid"><div className="profile-field"><label>Date de début</label><input type="date" required value={startDate} onChange={e=>setStartDate(e.target.value)}/></div><div className="profile-field"><label>Heure de début</label><input type="time" required value={startTime} onChange={e=>setStartTime(e.target.value)}/></div><div className="profile-field"><label>Date de fin</label><input type="date" required value={endDate} onChange={e=>setEndDate(e.target.value)}/></div><div className="profile-field"><label>Heure de fin</label><input type="time" required value={endTime} onChange={e=>setEndTime(e.target.value)}/></div></div></fieldset>
 <div className="profile-field"><label>Genre</label><input list="edit-genres" value={genre} onChange={e=>setGenre(e.target.value)}/><datalist id="edit-genres">{MUSIC_GENRES.map(g=><option key={g} value={g}/>)}</datalist></div><div className="profile-field"><label>Description</label><textarea rows={6} value={description} onChange={e=>setDescription(e.target.value)}/></div>
 <div className="profile-field event-banner-field"><label>Bannière</label>{bannerUrl?<img className="event-banner-preview" src={bannerUrl} alt="Bannière"/>:<div className="event-banner-placeholder"><ImagePlus/><span>Aucune bannière</span></div>}<label className="profile-avatar-button" htmlFor="edit-banner"><ImagePlus size={17}/>Remplacer la bannière</label><input id="edit-banner" className="profile-avatar-input" type="file" accept="image/jpeg,image/png,image/webp" onChange={banner}/></div>
 <div className="profile-field"><label>Capacité maximale</label><input type="number" min={1} required value={capacity} onChange={e=>setCapacity(e.target.value)}/></div>
 <fieldset className="ticket-phases"><div className="ticket-phases-title"><legend>Phases</legend><button type="button" disabled={total>=Number(capacity)} onClick={()=>setPhases(p=>[...p,{id:'',name:`Phase ${p.length+1}`,quantity:'',price:'',sold:0}])}><Plus size={16}/>Ajouter</button></div>{phases.map((phase,index)=><div className="ticket-phase-row" key={phase.id||`new-${index}`}><div className="profile-field"><label>Nom</label><input required value={phase.name} onChange={e=>setPhases(p=>p.map((x,i)=>i===index?{...x,name:e.target.value}:x))}/></div><div className="profile-field"><label>Places {phase.sold>0&&`(${phase.sold} vendues)`}</label><input type="number" required min={Math.max(1,phase.sold)} value={phase.quantity} onChange={e=>{const value=Number(e.target.value),others=total-Number(phase.quantity||0);if(value+others<=Number(capacity))setPhases(p=>p.map((x,i)=>i===index?{...x,quantity:e.target.value}:x))}}/></div><div className="profile-field"><label>Prix (€)</label><input type="number" required min={0} step=".01" value={phase.price} onChange={e=>setPhases(p=>p.map((x,i)=>i===index?{...x,price:e.target.value}:x))}/></div><button className="phase-remove" type="button" disabled={phases.length===1||phase.sold>0} onClick={()=>setPhases(p=>p.filter((_,i)=>i!==index))}><Trash2 size={17}/></button></div>)}<small>Total : {total} / {capacity||0}</small></fieldset>
 <div className="profile-field"><label>Publication</label><select value={publication} onChange={e=>setPublication(e.target.value as typeof publication)}><option value="draft">Brouillon</option><option value="now">Publiée</option><option value="scheduled">Programmée</option></select></div>{publication==='scheduled'&&<div className="event-form-grid scheduled-publication"><div className="profile-field"><label>Jour</label><input type="date" required value={publishDate} onChange={e=>setPublishDate(e.target.value)}/></div><div className="profile-field"><label>Heure</label><input type="time" required value={publishTime} onChange={e=>setPublishTime(e.target.value)}/></div></div>}
 {message&&<p className="profile-success">{message}</p>}{error&&<p className="profile-error">{error}</p>}<button className="cta profile-save" disabled={saving}>{saving?<LoaderCircle className="spin" size={18}/>:<Save size={18}/>}Enregistrer les modifications</button>
 </form></main>
}
