'use client';

import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { CreditCard, ExternalLink, LoaderCircle, Save } from 'lucide-react';
import { getSupabase } from '../../../lib/supabase-browser';

type Access='loading'|'guest'|'forbidden'|'ready';
type StripeStatus={connected:boolean;onboardingComplete:boolean;detailsSubmitted?:boolean;chargesEnabled:boolean;payoutsEnabled:boolean};

async function edgeErrorMessage(error:unknown,fallback:string){const candidate=error as {message?:string;context?:Response}|null;let detail=candidate?.message||fallback;if(candidate?.context)try{const payload=await candidate.context.clone().json();detail=payload.error||detail}catch{}return detail}

export default function OrganizerSettingsPage(){
  const [access,setAccess]=useState<Access>('loading'),[name,setName]=useState(''),[email,setEmail]=useState(''),[saving,setSaving]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  const [stripeStatus,setStripeStatus]=useState<StripeStatus|null>(null),[stripeLoading,setStripeLoading]=useState(false),[stripeError,setStripeError]=useState('');
  const [primaryFeeBps,setPrimaryFeeBps]=useState(350),[primaryFeeMinCents,setPrimaryFeeMinCents]=useState(49),[resaleFeeBps,setResaleFeeBps]=useState(1000),[resaleFeeCapCents,setResaleFeeCapCents]=useState(1500);
  useEffect(()=>{async function load(){const supabase=getSupabase();const {data:auth}=await supabase.auth.getUser();if(!auth.user){setAccess('guest');return}const {data:profile}=await supabase.from('profiles').select('role').eq('id',auth.user.id).single();if(profile?.role!=='organizer'){setAccess('forbidden');return}const {data:organization}=await supabase.from('organizer_profiles').select('name,primary_fee_bps,primary_fee_min_cents,resale_fee_bps,resale_fee_cap_cents').eq('profile_id',auth.user.id).maybeSingle();setName(organization?.name??'');setPrimaryFeeBps(organization?.primary_fee_bps??350);setPrimaryFeeMinCents(organization?.primary_fee_min_cents??49);setResaleFeeBps(organization?.resale_fee_bps??1000);setResaleFeeCapCents(organization?.resale_fee_cap_cents??1500);setEmail(auth.user.email??'');setAccess('ready');const {data,error}=await supabase.functions.invoke('create-connect-account-link',{body:{action:'status'}});if(error)setStripeError(await edgeErrorMessage(error,'Impossible de vérifier Stripe pour le moment.'));else setStripeStatus(data)}load()},[]);
  async function save(event:FormEvent){event.preventDefault();setSaving(true);setMessage('');setError('');const supabase=getSupabase();const {data:auth}=await supabase.auth.getUser();if(!auth.user){setError('Votre session a expiré.');setSaving(false);return}const {error:updateError}=await supabase.from('organizer_profiles').update({name:name.trim()}).eq('profile_id',auth.user.id);if(updateError)setError('Impossible d’enregistrer les paramètres.');else setMessage('Paramètres enregistrés.');setSaving(false)}
  async function stripeAction(action:'onboard'|'dashboard'){setStripeLoading(true);setStripeError('');const {data,error}=await getSupabase().functions.invoke('create-connect-account-link',{body:{action}});if(error||!data?.url)setStripeError(data?.error||await edgeErrorMessage(error,'Impossible d’ouvrir Stripe.'));else location.assign(data.url);setStripeLoading(false)}
  if(access==='loading')return <main className="dashboard"><p>Chargement…</p></main>;
  if(access==='guest')return <main className="dashboard organizer-access"><h1>Connectez-vous pour continuer.</h1><Link className="cta" href="/organizer/auth">Connexion organisateur</Link></main>;
  if(access==='forbidden')return <main className="dashboard organizer-access"><h1>Accès réservé aux organisations.</h1></main>;
  return <div className="pro-category-content"><header className="pro-category-header"><p className="eyebrow">PARAMÈTRES</p><h1>Votre organisation.</h1><p>Gérez les informations générales utilisées dans votre espace professionnel.</p></header><form className="pro-settings-card" onSubmit={save}><div className="profile-field"><label htmlFor="organization-name">Nom de l’organisation</label><input id="organization-name" required minLength={2} maxLength={100} value={name} onChange={event=>setName(event.target.value)}/></div><div className="profile-field"><label htmlFor="organization-email">Adresse de connexion</label><input id="organization-email" value={email} disabled/><small>La modification de l’adresse de connexion sera ajoutée ultérieurement.</small></div>{message&&<p className="profile-success">{message}</p>}{error&&<p className="profile-error">{error}</p>}<button className="cta profile-save" disabled={saving}>{saving?<LoaderCircle className="spin" size={18}/>:<Save size={18}/>}Enregistrer</button></form><section className="pro-settings-card organizer-fees-card"><p className="eyebrow">COMMISSIONS NOCTURNE</p><h2>Vos conditions commerciales</h2><div><span>Vente initiale<strong>{(primaryFeeBps/100).toLocaleString('fr-FR')} %</strong><small>Minimum {(primaryFeeMinCents/100).toLocaleString('fr-FR',{style:'currency',currency:'EUR'})} par billet</small></span><span>Revente<strong>{(resaleFeeBps/100).toLocaleString('fr-FR')} %</strong><small>Plafond {(resaleFeeCapCents/100).toLocaleString('fr-FR',{style:'currency',currency:'EUR'})} par billet</small></span></div><small>Ces conditions sont définies contractuellement par NOCTURNE et ne sont pas modifiables depuis votre compte.</small></section><section className="pro-settings-card stripe-connect-card"><div className="stripe-connect-heading"><CreditCard/><div><p className="eyebrow">PAIEMENTS</p><h2>Stripe Connect</h2></div><span className={stripeStatus?.onboardingComplete?'stripe-status ready':'stripe-status'}>{stripeStatus?.onboardingComplete?'Opérationnel':stripeStatus?.connected?'À terminer':'Non connecté'}</span></div><p>Connectez directement le compte bancaire de votre organisation pour recevoir les ventes et gérer les virements.</p>{stripeStatus?.connected&&!stripeStatus.onboardingComplete&&<ul className="stripe-requirements"><li className={stripeStatus.detailsSubmitted?'done':''}>Informations de l’organisation</li><li className={stripeStatus.chargesEnabled?'done':''}>Encaissements activés</li><li className={stripeStatus.payoutsEnabled?'done':''}>Virements activés</li></ul>}{stripeError&&<p className="profile-error">{stripeError}</p>}<button type="button" className="cta profile-save" disabled={stripeLoading} onClick={()=>void stripeAction(stripeStatus?.onboardingComplete?'dashboard':'onboard')}>{stripeLoading?<LoaderCircle className="spin" size={18}/>:<ExternalLink size={18}/>} {stripeStatus?.onboardingComplete?'Ouvrir Stripe':'Configurer Stripe'}</button></section></div>;
}
