'use client';
import { FormEvent, useEffect, useState } from 'react';
import Link from 'next/link';
import { ArrowLeft, ArrowRight, Building2, LoaderCircle } from 'lucide-react';
import { getSupabase } from '../../../lib/supabase-browser';

export default function OrganizerAuthPage(){
 const [signup,setSignup]=useState(false),[organization,setOrganization]=useState(''),[email,setEmail]=useState(''),[password,setPassword]=useState(''),[loading,setLoading]=useState(false),[message,setMessage]=useState('');
 useEffect(()=>{async function detect(){const supabase=getSupabase();const {data:auth}=await supabase.auth.getUser();if(!auth.user)return;const {data}=await supabase.from('profiles').select('role').eq('id',auth.user.id).single();if(data?.role==='admin')location.assign('/admin/dashboard');else if(['organizer_pending','organizer'].includes(data?.role))location.assign('/organizer/dashboard')}detect()},[]);
 async function submit(event:FormEvent){event.preventDefault();setLoading(true);setMessage('');try{const supabase=getSupabase();if(signup){const {error}=await supabase.auth.signUp({email,password,options:{data:{account_type:'organizer',organization_name:organization},emailRedirectTo:`${location.origin}/organizer/auth`}});if(error)throw error;setMessage('Vérifiez votre e-mail. Votre espace professionnel sera ensuite soumis à validation.');}else{const {data,error}=await supabase.auth.signInWithPassword({email,password});if(error)throw error;const {data:profile}=await supabase.from('profiles').select('role').eq('id',data.user.id).single();if(profile?.role==='admin'){await supabase.auth.signOut();throw new Error('Utilisez la connexion dédiée à l’administration NOCTURNE.')}if(!profile||!['organizer_pending','organizer'].includes(profile.role)){await supabase.auth.signOut();throw new Error('Ce compte est un compte utilisateur classique. Utilisez la connexion Mon compte.')}location.assign('/organizer/dashboard')}}catch(error){setMessage(error instanceof Error?error.message:'Connexion impossible.')}finally{setLoading(false)}}
 return <main className="pro-auth-page"><nav className="pro-auth-nav"><Link className="pro-brand" href="/organizer/auth">NOCTURNE<span>°</span><small>ORGANISATION</small></Link><Link className="profile-back profile-nav-back" href="/"><ArrowLeft size={16}/>Retour au site public</Link></nav><section className="pro-auth-layout"><div className="pro-auth-intro"><Building2 size={28}/><p className="eyebrow">ESPACE PROFESSIONNEL</p><h1>La nuit commence ici.</h1><p>Créez vos soirées, gérez votre programmation et suivez vos ventes depuis un espace conçu pour les organisations.</p></div><div className="pro-auth-card"><p className="eyebrow">{signup?'CRÉER UNE ORGANISATION':'CONNEXION ORGANISATEUR'}</p><h2>{signup?'Ouvrir un espace pro':'Bienvenue.'}</h2><form onSubmit={submit}>{signup&&<label>Nom de l’organisation<input required maxLength={120} value={organization} onChange={e=>setOrganization(e.target.value)}/></label>}<label>E-mail professionnel<input required type="email" value={email} onChange={e=>setEmail(e.target.value)}/></label><label>Mot de passe<input required minLength={8} type="password" value={password} onChange={e=>setPassword(e.target.value)}/></label><button disabled={loading}>{loading?<LoaderCircle className="spin" size={18}/>:<ArrowRight size={18}/>} {signup?'Créer mon espace':'Accéder à mon espace'}</button></form>{message&&<p className="auth-message">{message}</p>}<p className="switch">{signup?'Déjà une organisation ?':'Première soirée sur NOCTURNE ?'} <button onClick={()=>{setSignup(!signup);setMessage('')}}>{signup?'Se connecter':'Créer un compte organisateur'}</button></p><small className="pro-auth-note">Cet accès est réservé aux comptes organisation et administration.</small></div></section></main>
}
